services:
  - type: web
    name: notes-app-backend
    env: java
    buildCommand: cd backend && mvn clean package -DskipTests
    startCommand: cd backend && java -jar target/notes-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_PASSWORD
        value: Nope2@13
      - key: FRONTEND_URL
        value: https://simple-notes-app-inky.vercel.app
      - key: SPRING_PROFILES_ACTIVE
        value: prod